# .kiro/hooks/security-scan.yml
trigger: 'pre_commit'

actions:
  - name: 'Check for secrets'
    command: 'git secrets --scan'

  - name: 'Dependency audit'
    command: 'npm audit'
    severity_threshold: 'moderate'
